spring.application.name=ecommerce-backend

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/ecommerce_db

# JWT properties
jwt.secret=94a08da1fecbb6e8b46990538c7b50b2a75ef293503f27f88417eb6cb7f920da
jwt.expirationMs=86400000

# File Upload Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
app.upload.dir=uploads
